__title__ = 'Sema4.AI handler'
__package_name__ = 'mindsdb_sema4_handler'
__version__ = '0.0.2'
__description__ = "MindsDB handler for Sema4"
__author__ = 'Sema4.AI Inc'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023- mindsdb'
